version: "3.9"

x-default-service: &common
  network_mode: host
  volumes:
    - ~/.ccache:/home/devel/.ccache
    - /tmp/.X11-unix/:/tmp/.X11-unix/
    - ~/.Xauthority:/home/ivision/.Xauthority
    - ~/Downloads/cuda-samples:/home/ivision/cuda-samples
  working_dir: /home/ivision/cuda-samples
  tty: true
  stdin_open: true
  environment:
    - DISPLAY
    - NVIDIA_DRIVER_CAPABILITIES=all
  cap_add:
      - SYS_PTRACE

x-app: &default-apps
  USER_NAME: "ivision"
  QT_VERSION: 6.2.4
  QTCREATOR_VERSION: 5.0.3
  BAT_VERSION: 0.22.1
  RIPGREP_VERSION: 13.0.0
  GLOW_VERSION: 1.4.1
  OPENCV_VERSION: 4.5.3
  BOOST_VERSION: "1_77_0"

services:

  ivsn-qt6:
    << : *common
    image: ${DOCKER_USER:-ivision}/ivsn_dev:${DOCKER_TAG:-bionic-qt6-6.2.4-devcomm}
    build:
      dockerfile: docker/${UBUNTU_DIST:-bionic}/${DOCKERFILE:-Dockerfile}
      context: .
      target: ${TARGET_STAGE:-base-devcomm}
      args:
        << : *default-apps

  dev_cuda:
    image: ivision/ivsn_dev:focal-qt6-6.2.4-cuda-11.3
    container_name: dev_cuda
    << : *common
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
